- hosts: localhost
  connection: local
  tasks:
    - name: Generating certificates
      command: ./gen-pki.sh
      tags:
        - never
        - gen-pki


- hosts: all
  tasks:
    - name: Copying certificates to machines (1/2)
      copy:
        src: "pki/{{ item }}"
        dest: ~/
      loop:
        - "{{ inventory_hostname }}.pem"
        - "{{ inventory_hostname }}-key.pem"
        - "ca.pem"
      when: "'workers' in group_names"

    - name: Copying certificates to machines (2/2)
      copy:
        src: "pki/{{ item }}"
        dest: ~/
      loop:
        - "ca.pem"
        - "ca-key.pem"
        - "kubernetes.pem"
        - "kubernetes-key.pem"
        - "service-account.pem"
        - "service-account-key.pem"
      when: "'controllers' in group_names"