- hosts: localhost
  connection: local
  tasks:
    - name: Get Public IP
      uri:
        url: https://ifconfig.me/ip
        method: GET
        return_content: yes
      register: pub_ip
    
    - name: Set Public IP fact (localhost)
      set_fact:
        k8s_public_ip: "{{ pub_ip.content }}"
    
    - debug:
        var: k8s_public_ip

- hosts: all
  tasks:
    - name: Set Public IP fact (all)
      set_fact:
        k8s_public_ip: "{{ hostvars['localhost']['k8s_public_ip'] }}"

    - name: Copying certificates to machines (1/2)
      copy:
        src: "pki/{{ item }}"
        dest: ~/
      loop:
        - "{{ inventory_hostname }}.pem"
        - "{{ inventory_hostname }}-key.pem"
        - "ca.pem"
      when: "'workers' in group_names"

    - name: Copying certificates to machines (2/2)
      copy:
        src: "pki/{{ item }}"
        dest: ~/
      loop:
        - "ca.pem"
        - "ca-key.pem"
        - "kubernetes.pem"
        - "kubernetes-key.pem"
        - "service-account.pem"
        - "service-account-key.pem"
      when: "'controllers' in group_names"
