- hosts: localhost
  connection: local
  tasks:
    - name: Create .tmp folder
      file:
        path: .tmp
        state: directory

    - name: Generate kubelet config files
      changed_when: false
      shell: |
        kubectl config set-cluster {{ k8s_cluster_name }} \
          --certificate-authority=pki/ca.pem \
          --embed-certs=true \
          --server=https://{{ k8s_public_ip }}:6443 \
          --kubeconfig=.tmp/{{ item }}.kubeconfig

        kubectl config set-credentials system:node:{{ item }} \
          --cluster={{ k8s_cluster_name }} \
          --user=system:node:{{ item }} \
          --kubeconfig=.tmp/{{ item }}.kubeconfig

        kubectl config set-context default \
          --cluster={{ k8s_cluster_name }} \
          --user=system:node:{{ item }} \
          --kubeconfig=.tmp/{{ item }}.kubeconfig

        kubectl config use-context default --kubeconfig=.tmp/{{ item }}.kubeconfig
      loop: "{{ k8s_wrk_nodes }}"

    - name: Generate kube-proxy config file
      changed_when: false
      shell: |
        kubectl config set-cluster {{ k8s_cluster_name }} \
          --certificate-authority=ca.pem \
          --embed-certs=true \
          --server=https://{{ k8s_public_ip }}:6443 \
          --kubeconfig=.tmp/kube-proxy.kubeconfig

        kubectl config set-credentials system:kube-proxy \
          --client-certificate=kube-proxy.pem \
          --client-key=kube-proxy-key.pem \
          --embed-certs=true \
          --kubeconfig=.tmp/kube-proxy.kubeconfig

        kubectl config set-context default \
          --cluster={{ k8s_cluster_name }} \
          --user=system:kube-proxy \
          --kubeconfig=.tmp/kube-proxy.kubeconfig

        kubectl config use-context default --kubeconfig=.tmp/kube-proxy.kubeconfig

    - name: Generate kube-controller-manager config file
      changed_when: false
      shell: |
        kubectl config set-cluster {{ k8s_cluster_name }} \
          --certificate-authority=ca.pem \
          --embed-certs=true \
          --server=https://127.0.0.1:6443 \
          --kubeconfig=.tmp/kube-controller-manager.kubeconfig

        kubectl config set-credentials system:kube-controller-manager \
          --client-certificate=kube-controller-manager.pem \
          --client-key=kube-controller-manager-key.pem \
          --embed-certs=true \
          --kubeconfig=.tmp/kube-controller-manager.kubeconfig

        kubectl config set-context default \
          --cluster={{ k8s_cluster_name }} \
          --user=system:kube-controller-manager \
          --kubeconfig=.tmp/kube-controller-manager.kubeconfig

        kubectl config use-context default --kubeconfig=.tmp/kube-controller-manager.kubeconfig

    - name: Generate kube-scheduler config file
      changed_when: false
      shell: |
        kubectl config set-cluster {{ k8s_cluster_name }} \
          --certificate-authority=ca.pem \
          --embed-certs=true \
          --server=https://127.0.0.1:6443 \
          --kubeconfig=.tmp/kube-scheduler.kubeconfig

        kubectl config set-credentials system:kube-scheduler \
          --client-certificate=kube-scheduler.pem \
          --client-key=kube-scheduler-key.pem \
          --embed-certs=true \
          --kubeconfig=.tmp/kube-scheduler.kubeconfig

        kubectl config set-context default \
          --cluster={{ k8s_cluster_name }} \
          --user=system:kube-scheduler \
          --kubeconfig=.tmp/kube-scheduler.kubeconfig

        kubectl config use-context default --kubeconfig=.tmp/kube-scheduler.kubeconfig

    - name: Generate admin config file
      changed_when: false
      shell: |
        kubectl config set-cluster {{ k8s_cluster_name }} \
          --certificate-authority=ca.pem \
          --embed-certs=true \
          --server=https://127.0.0.1:6443 \
          --kubeconfig=.tmp/admin.kubeconfig

        kubectl config set-credentials admin \
          --client-certificate=admin.pem \
          --client-key=admin-key.pem \
          --embed-certs=true \
          --kubeconfig=.tmp/admin.kubeconfig

        kubectl config set-context default \
          --cluster={{ k8s_cluster_name }} \
          --user=admin \
          --kubeconfig=.tmp/admin.kubeconfig

        kubectl config use-context default --kubeconfig=.tmp/admin.kubeconfig

- hosts: controllers
  tasks:
    - name: Copying configs (controllers)
      copy:
        src: .tmp/{{ item }}.kubeconfig
        dest: ~/
      loop:
        - admin
        - kube-controller-manager
        - kube-scheduler

- hosts: workers
  tasks:
    - name: Copying configs (workers)
      copy:
        src: .tmp/{{ item }}.kubeconfig
        dest: ~/
      loop:
        - "{{ inventory_hostname_short }}"
        - kube-proxy